# TODO check this out:
# xsetroot -cursor_name left_ptr

xset b 0 0 0
xset r rate 400 30

xhost +SI:localuser:$USER

# Make Java applications aware this is a non-reparenting window manager.
export _JAVA_AWT_WM_NONREPARENTING=1

# Set default cursor.
xsetroot -cursor_name left_ptr

# fonts
fc-cache -fv

exec exwm
