(specifications->manifest
 '(
   "font-jetbrains-mono"
   "font-google-noto"
   "font-iosevka"
   "font-iosevka"
   "font-inconsolata"
   "font-hack"
   "font-openmoji"
   "unicode-emoji"
   "font-gnu-unifont"
   "font-adobe75dpi"
   ))
